
export const productActions = {
    ADD_PRODUCT: 'ADD_PRODUCT',
    DELETE_PRODUCT: 'DELETE_PRODUCT',
    UPDATE_PRODUCT: 'UPDATE_PRODUCT',

    GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS',
    GET_ALL_FAILURE: 'GET_ALL_FAILURE',

}